name: Reusable Workflow

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string

jobs:
  print-name:
    runs-on: ubuntu-latest
    steps:
      - name: Print Input Name
        run: echo "Hello, ${{ inputs.name }}!"
